# Generated by Django 4.0.5 on 2022-06-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_menu_mainphoto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='mainphoto',
        ),
    ]
